### PR TITLE
Update blockchain service name & remove host param in order to make d2bm v2 work

### PR DESCRIPTION
**Pull request by szbra**
Please contact Szymon.Brandys@pl.ibm.com for questions

### CODE REVIEW

**Comment by dshuffma-ibm** [comment]
I've taken the plan upgrade thanks for that, it changed today.  

I cannot take the manifest file change.  We want an example file for most Bluemix users.  Thus we need the host line for a complete example.  The tutorial instructs people to modify the host name to a unique name.

**Comment by szbra** [comment]
If the host is removed from the manifest, the example will still work fine when pushing using cf push, The name will be used as the host.

The problem is that with host, users will hit "host is taken" when they start using new Deploy2Bluemix v2.

**Comment by dshuffma-ibm** [comment]
ah I did not know that, seems to be okay. Thanks!

**Comment by szbra** [comment]
Thanks!

**Pull request merged**
